export const GamifiedUserAction = {
  CREATE_PLANT: 'CREATE_PLANT',
  CREATE_PLANT_WITH_OPTIONAL_FIELDS: 'CREATE_PLANT_WITH_OPTIONAL_FIELDS',
  UPVOTE_PLANT: 'UPVOTE_PLANT',
  EVALUATE_COMPLAINT: 'EVALUATE_COMPLAINT',
  COMPLETE_PROFILE: 'COMPLETE_PROFILE',
}
export const ExperiencePerAction = {
  CREATE_PLANT: 15,
  CREATE_PLANT_WITH_OPTIONAL_FIELDS: 25,
  UPVOTE_PLANT: 2,
  EVALUATE_COMPLAINT: 20,
  COMPLETE_PROFILE: 30,
}
